### ISSUE TITLE
Consider supporting multiple path arguments

### ISSUE THREAD

**Issue by dtolnay** [DevinR528/cargo-sort-ck#1]
```console
$ cargo-sort-ck -w path/to/first path/to/second ...
```

This would also play nicely with wildcard expansions provided by the shell:

```console
$ cargo-sort-ck rust/src/*/Cargo.toml
```

@DevinR528

**Comment by DevinR528** [comment]
That's handy, I didn't know you could do that.  Great feature, it now supports wildcard expansion.
