### ISSUE TITLE
Feature Request: Flag to sort the entire workspace

### ISSUE THREAD

**Issue by msrd0** [DevinR528/cargo-sort-ck#11]
Most cargo subcommands have a `--workspace` flag that applies them to all crates in the workspace, not just the root crate. However, it seems that `cargo sort-ck` currently only checks the root crate, and therefore needs to be invoked on every directory in the workspace. It would be nice if it also supported checking all crates in the workspace with just one command.

**Comment by DevinR528** [comment]
Oh yeah, this would be a great addition! Are you interested in opening a PR, if not I can look into this in the next few days hopefully?

**Comment by msrd0** [comment]
I guess this isn't too hard to implement so I can try to create a PR. It looks like this is roughly what needs to be done:

 - Add a `--workspace` flag to the command line parsing
 - If set, inspect the `Cargo.toml` file of the current directory to see if it contains any `package.workspace` settings, otherwise assume that the current directory is the workspace root
 - Inspect the `Cargo.toml` file at the root and include all directories listed in `workspace.members`
 - Expand any globs that were part of the `members` list
 - Remove any packages excluded by `workspace.exclude` (this list doesn't seem to support globs)

Looking at your code, everything seems straight-forward except reading stuff from the `Cargo.toml` files. Do you know how I can extract data from toml files using the toml library you are currently using, or do I need to use some other library for that?

**Comment by DevinR528** [comment]
Yeah that sounds about right to me. I looked through what I have https://github.com/DevinR528/toml-parse, I think it may be as simple as uncommenting https://github.com/DevinR528/toml-parse/blob/main/src/lib.rs#L8 I do remember using it without problems :shrug:

**Comment by DevinR528** [comment]
I opened a PR to enable the `struc` mod exporting and some other cleanup https://github.com/DevinR528/toml-parse/pull/6

I want to test it out in sort check before I release it just to be sure.

**Comment by clintfred** [comment]
I see that https://github.com/DevinR528/toml-parse/pull/6 was closed and not merged. Is this still a planned feature? Thanks!

**Comment by DevinR528** [comment]
Yeah still planning on adding the `--workspace` feature. I've been trying to use the [toml-edit](https://github.com/ordian/toml_edit) crate instead of my own parser. This would be great since the whole toml-parse could be reduced to this basically https://github.com/DevinR528/toml-parse/blob/rework-sort/src/toml.rs

**Comment by DevinR528** [comment]
https://github.com/DevinR528/cargo-sort-ck/pull/13 will solve all our problems :laughing:
