### ISSUE TITLE
Idea: Rename to cargo-sort

### ISSUE THREAD

**Issue by jplatte** [DevinR528/cargo-sort-ck#15]
I find it a bit weird that currently to sort the dependencies in a `Cargo.toml`, the invocation is `cargo sort-ck --write` rather than just `cargo sort` (mirroring `cargo fmt` or `cargo fix`).

So I want to propose to rename this tool `cargo sort` and have it default to updating `Cargo.toml` with the current default behaviour being changed to a flag (`cargo sort --check`, similar to `cargo fmt -- --check`).

**Comment by jplatte** [comment]
Alternatively, two binaries could be provided, so that both `cargo sort` and `cargo sort-ck` are possible.

**Comment by DevinR528** [comment]
I do like the shorter name and keeping it consistent with the other cargo tools makes sense (bonus cargo-sort is available on crates.io). If I just go with one binary do I just rename it in the `Cargo.toml` to publish it under the new name? Would this give me two binaries on crates.io

```toml
[[bin]]
name = "cargo-sort"
path = "src/sort.rs"

[[bin]]
name = "cargo-sort-ck"
path = "src/check.rs"
```

If it's going to write by default I'm wondering about a format config file :disappointed:? `toml_edit` would probably have to be forked I doubt the maintainer would be ok with leaking that much internal API stuff. would we still want the grouped key values like in `ruma` or if we could format remove all the double line breaks?

**Comment by jplatte** [comment]
> If I just go with one binary do I just rename it in the `Cargo.toml` to publish it under the new name? Would this give me two binaries on crates.io

Yes and yes.

> would we still want the grouped key values like in `ruma` or if we could format remove all the double line breaks?

For ruma I would prefer keeping the grouping, but would probably also be fine removing it, whether or not cargo-sort(-ck) is able to remove whitespace automatically (the much important thing is the CI check, not the rewriting part).

**Comment by DevinR528** [comment]
Any thoughts on the best way to fork and use `toml_edit` from this crate so I can still publish to crates.io? Just move it in as a module like urlencoded in ruma?

**Comment by jplatte** [comment]
> Any thoughts on the best way to fork and use `toml_edit` from this crate so I can still publish to crates.io? Just move it in as a module like urlencoded in ruma?

Yeah, why not, if you need to fork.
