### ISSUE TITLE
Only content requested by the user should go to stdout

### ISSUE THREAD

**Issue by dtolnay** [DevinR528/cargo-sort-ck#2]
Everything else should go to stderr. For example:

```
$ cargo-sort-ck -p > Cargo.sorted.toml
```

This currently unexpectedly puts an invalid line at the top of the file. (Worse, the line contains color control characters.)

@DevinR528

**Comment by dtolnay** [comment]
In the case of `-p` it would be better to omit the current first line entirely when stdout is not a tty.

**Comment by DevinR528** [comment]
Yea, this makes more sense. Removing the print now!

@dtolnay Thank you for the feedback, and encouragement I really appreciate it.
