### ISSUE TITLE
Fails as cargo subcommand

### ISSUE THREAD

**Issue by dspicher** [DevinR528/cargo-sort-ck#4]
When invoked as a subcommand, `cargo sort-ck` fails because of how cargo passes on the command name as an argument:

"When Cargo invokes a custom subcommand, the first argument to the subcommand will be the filename of the custom subcommand, as usual. The second argument will be the subcommand name itself. For example, the second argument would be ${command} when invoking cargo-${command}. Any additional arguments on the command line will be forwarded unchanged."

https://doc.rust-lang.org/cargo/reference/external-tools.html#custom-subcommands

```
╰─$ cargo sort-ck                                                                                                                                                                                     101 ↵
Failure: No file found at: sort-ck/Cargo.toml
```

Is there a way to make the arguments to `cargo-sort-ck` consistent with how `cargo` passes them to subcommands?

**Comment by DevinR528** [comment]
First thank you for your interest.

Yea I was hoping I could get this to work when I first wrote this. I filed an [issue](https://github.com/rust-lang/cargo/issues/7653) with the cargo repo because every other crate that works as a subcommand seems to be doing the same things as this crate, I will keep investigating.

**Comment by DevinR528** [comment]
This [commit](https://github.com/DevinR528/cargo-sort-ck/commit/1b4453717aaefd264f8dbcd1dc8d7337ca22510b#diff-639fbc4ef05b315af92b4d836c31b023) if your curious fixes issue #4. Hope that works if you update your `cargo-sort-ck` version you should be good to go I published a new release.

**Comment by dspicher** [comment]
Just tested it, confirmed fixed. Thanks a lot for the quick response!!

**Comment by dspicher** [comment]
And thanks for the shoutout on the REAMDE :))
